[package]
name = "km2rasberrypi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
evdev = "0.12.1"
getset = "0.1.2"
toml_edit = "0.21.0"

[build-dependencies]
bindgen = "0.69.1"
